Repository ujohnwesly8/LeapApp, pull requests merged in 2023-06, with the labels that each got.

#169 changes done
  README.md
  src/components/atoms/AnalyticsDropdown/AnalyticsDropdown.tsx
Labels: fix

#171 resolved a minor bug
  .scannerwork/report-task.txt
  src/constants/Apis.ts
Labels: fix

#172 Sonar major bugs
  .scannerwork/report-task.txt
  src/redux/reducers/EditProductsReducers.tsx
  src/screens/Owneredititems/Useowneredititems.ts
Labels: fix

#174 completed minor bugs part based on sonarqube
  .scannerwork/report-task.txt
  src/constants/Apis.ts
  src/screens/OwnerHomepage/DashboardDetails.tsx
Labels: fix

#178 fix(outfit-dropdown):changed the outfit dropdown to custom dropdown
  src/screens/Additems/Additems.tsx
Labels: fix

#179 resolved 10 major bugs based on sonarqube
  .scannerwork/report-task.txt
  src/components/atoms/AnalyticsDatePicker.tsx
  src/components/atoms/CalanderPicker.tsx
  src/components/atoms/DatePicker.tsx
  src/screens/FilteredAnalytics/FilteredAnalytics.tsx
  src/screens/OwnerHomepage/DashboardDetails.tsx
  src/screens/Owneredititems/Owneredititems.tsx
Labels: fix

#180 fix(edititems-dropdowns): changed the edit items dropdowns
  src/screens/Owneredititems/Owneredititems.tsx
Labels: fix

#182 resolved a major bug in profile based on sonarqube
  .scannerwork/report-task.txt
  ColorSchemeContext.js
  CustomModalContext.tsx
  src/screens/Profile/Profile.tsx
Labels: fix

#184 resolved a major bug in useOwnerHome of empty block
  .scannerwork/report-task.txt
  src/screens/OwnerHomepage/useOwnerHome.ts
Labels: fix

#185 resolved array index in keys in Uproductdetailspage
  src/screens/UProductDetails/UProductDetails.tsx
Labels: fix

#186 resolved a major bug in images of Owneredititems
  .scannerwork/report-task.txt
  src/screens/Owneredititems/Owneredititems.tsx
Labels: fix

#188 CategoryProducts_Majorerror fixed
  src/screens/CategoryProducts/CategoryProducts.tsx
Labels: fix

#191 fix : Custom DatePicker for cart and userdetails screens
  src/components/atoms/DatePicker.tsx
  src/components/atoms/DatePickerComponent/DatepickerComponent.tsx
  src/components/atoms/DatePickerComponent/datepickerStyles.ts
  src/screens/Cart/Cart.tsx
  src/screens/Cart/CartItemStyles.ts
  src/screens/UProductDetails/UProductDetails.tsx
  src/screens/UProductDetails/UProductDetailsStyle.ts
Labels: fix

#193 fix: critical error for ownerhome is fixed
  CustomModalContext.tsx
  src/screens/OwnerHomepage/OwnerHome.tsx
  src/screens/OwnerHomepage/OwnerHomestyle.ts
  src/screens/OwnerHomepage/useOwnerHome.ts
Labels: fix

#194 removed duplicated lines from owner home page
  src/constants/Apis.ts
  src/screens/OwnerHomepage/OwnerHome.tsx
Labels: fix

#197 Owner home critical error
  src/screens/OwnerHomepage/OwnerHome.tsx
Labels: fix

#198 fixed a bug of refactoring of Ownereditprofile page has been done
  .scannerwork/report-task.txt
  src/redux/reducers/Additemsreducers.tsx
  src/screens/Ownereditprofile/OwnerEditProfile.tsx
  src/screens/Subcategory/Subcategory.tsx
Labels: fix

#199 fix : major bug fixed active index in cart
  src/screens/Cart/Cart.tsx
Labels: fix

#201 resolved a major bug and critical bugs in ownerstack
  .scannerwork/report-task.txt
  src/navigation/Ownerbottomtab/Ownerstack.tsx
Labels: fix

#204 fixed the nested ternary operator critical error
  src/screens/FilteredAnalytics/FilteredAnalytics.tsx
Labels: fix

#205 fix(error): Cognitive comlexity error resolved in edit address
  .scannerwork/report-task.txt
  ColorSchemeContext.js
  src/screens/EditAddress/EditAddress.tsx
Labels: fix

#206 resolved major bugs and added order function
  .prettierrc.js
  .scannerwork/report-task.txt
  src/constants/Apis.ts
  src/redux/actions/actions.ts
  src/redux/reducers/Orderreducer.tsx
  src/screens/Cart/Cart.tsx
  src/screens/Cart/CartItemStyles.ts
  src/screens/Cart/useCart.tsx
  src/screens/CheckoutScreen/CheckoutScreen.tsx
  src/screens/CheckoutScreen/CheckoutScreenStyle.ts
  src/screens/CheckoutScreen/useCheckout.ts
Labels: fix

#208 fix(error): Cognitive error resolved in Search Results Screen
  ColorSchemeContext.js
  src/constants/Apis.ts
  src/screens/CheckoutScreen/CheckoutScreen.tsx
  src/screens/CheckoutScreen/CheckoutScreenStyle.ts
  src/screens/CheckoutScreen/useCheckout.ts
  src/screens/EditAddress/EditAddress.tsx
  src/screens/SearchResultScreen/SearchResultScreen.tsx
Labels: fix

#210 fix(error): Owner Profile Page cognitive error is fixed
  src/screens/Ownerprofile/OwnerProfile.tsx
Labels: fix

#211 refactor the homescreen and reduce cognitive complexity
  .scannerwork/report-task.txt
  src/constants/Apis.ts
  src/screens/EditAddress/editAddressStyles.ts
  src/screens/EditAddress/useEditAddress.ts
  src/screens/Home/Homescreen.tsx
Labels: fix

#213 fix(error): OwnerEditItems cognitive error is fixed
  .scannerwork/report-task.txt
  src/screens/Owneredititems/Owneredititems.tsx
Labels: fix

#214 Addimages Cognitive Complexity error fixed
  src/screens/OwnerImage/AddImages.tsx
Labels: fix

#217 Analtyics Cirtical error is Fixed
  .scannerwork/report-task.txt
  src/constants/Apis.ts
  src/screens/OwnerHomepage/DashboardDetails.tsx
Labels: fix

#221 fix(duplicates):removed duplications in the owner products details
  .scannerwork/report-task.txt
  src/screens/OwnerProductdetailsPage/oProductDetailsStyle.ts
Labels: fix

#222 resolved a Major Bug in DetailsDashboard
  .scannerwork/report-task.txt
  src/screens/OwnerHomepage/DashboardDetails.tsx
Labels: fix

#223 fix: type error in AnalyticsDatePicker
  src/components/atoms/AnalyticsDatePicker.tsx
Labels: fix

#224 Duplications fixes
  src/screens/CheckoutScreen/CheckoutScreenStyle.ts
Labels: fix

#225 Resolved duplication on categoryproducts page and wishlist page
  .scannerwork/report-task.txt
  src/screens/CategoryProducts/CategoryProducts.tsx
Labels: Duplications fix

#226 fix: type error in DonutChart
  src/components/atoms/DonutChart.tsx
Labels: fix

#227 removed duplications from AnalyticsDatePicker
  src/components/atoms/AnalyticsDatePicker.tsx
Labels: duplicate

#228 resolved a duplication error in Profile and OwnerProfile
  .scannerwork/report-task.txt
  src/screens/Ownerprofile/OwnerProfile.tsx
Labels: Duplications fix

#229 fix: type error in Sizeselect
  src/components/atoms/GenderDropdown.tsx
  src/components/atoms/Sizeselect.tsx
Labels: fix

#230 fix: type error in SwitchAccountButtob
  src/components/atoms/SwtichAccountButton.tsx
Labels: fix

#231 fix: type error in HeadingText
  src/components/atoms/HeadingText/HeadingTest.tsx
Labels: fix

#232 Security errors
  package-lock.json
  package.json
  src/screens/FilteredAnalytics/FilteredAnalytics.tsx
  src/screens/FilteredAnalytics/useFilteredAnalytics.ts
  src/screens/OwnerHomepage/DashboardDetails.tsx
Labels: bug, fix

#233 fix: type error in CutomModel done
  src/components/atoms/CustomModel/CustomModel.tsx
Labels: fix

#234 removed type error from checkout
  src/screens/CheckoutScreen/useCheckout.ts
Labels: fix

#235 fix: type error in DatepickerComponent is done
  .scannerwork/report-task.txt
  src/components/atoms/DatePickerComponent/DatepickerComponent.tsx
Labels: fix

#237 fix(error): size dropdown type errors resolved
  src/components/atoms/Sizeselect.tsx
  src/constants/Apis.ts
Labels: fix

#238 fix: Custom modal in sign in page fixed
  src/screens/LoginScreen/useLoginscreen.ts
Labels: fix

#239 skeliton loader color error fixed
  src/screens/Additems/Additems.tsx
Labels: fix

#240 resolved a colorschema textInput textcolor bug is fixed
  src/screens/Ownereditprofile/OwnerEditProfile.tsx
  src/screens/Wishlist/wishlistStyles.ts
Labels: fix

#241 code after screening
  src/components/atoms/Sizeselect.tsx
  src/constants/Apis.ts
  src/screens/Category/categoryStyles.ts
  src/screens/CategoryProducts/CategoryProducts.tsx
  src/screens/OwnerHomepage/DashboardDetails.tsx
  src/screens/OwnerImage/AddImages.tsx
  src/screens/UProductDetails/useProductdetails.ts
Labels: code change

#242 created atom folder in testing and working in backbutton
  __tests__/atoms/BackButton/BackButton.test.tsx
  __tests__/atoms/Headingtext/Headingtext.test.tsx
Labels: Component Test

#243 testing : CustomModel_testing is done
  __tests__/atoms/CustomModel/CustomModel.test.tsx
  __tests__/atoms/CustomModel/CustomModelStyles.test.ts
Labels: Component Test

#244 resolved every code smells after screening
  .scannerwork/report-task.txt
  __tests__/atoms/BackButton/BackButton.test.tsx
  __tests__/atoms/Headingtext/Headingtext.test.tsx
  assets/darkmoon.jpeg
  assets/moon.json
  assets/sun.json
  assets/sun.png
  package.json
  src/components/atoms/Colorscheme/Togglebutton.tsx
  src/constants/Apis.ts
  src/screens/OwnerHomepage/DashboardDetails.tsx
  src/screens/OwnerImage/AddImages.tsx
  src/screens/Ownereditprofile/OwnerEditProfile.tsx
Labels: fix

#245 backbutton testing completed
  .gitignore
  __tests__/atoms/BackButton/BackButton.test.tsx
  __tests__/atoms/Headingtext/Headingtext.test.tsx
  sonar-project.properties
  src/components/atoms/BackButton/BackButton.tsx
  src/components/atoms/HeadingText/HeadingTest.tsx
  src/constants/Apis.ts
  src/screens/FilteredAnalytics/FilteredAnalytics.tsx
  src/screens/FilteredAnalytics/useFilteredAnalytics.ts
  src/screens/OwnerHomepage/DashboardDetails.tsx
Labels: code change, Component Test

#247 test: Subcategory Dropdown testing done
  __tests__/atoms/SubcategoryDropdown/SubcategoryDropodown.test.tsx
  src/components/atoms/SubcategoryDropdown/SubcategoryDropdown.tsx
Labels: code change, Component Test

#249 Headingtext,Pricedropdown,filtersizedropdown testing is done
  .scannerwork/report-task.txt
  __tests__/atoms/Filtersize/Filtersizes.test.tsx
  __tests__/atoms/Pricedropdown/Pricedropdown.test.tsx
  sonar-project.properties
  src/components/atoms/FilterSizes/FilterSizeSelect.tsx
  src/components/atoms/PriceRange/PriceDropdown.tsx
  src/screens/OwnerHomepage/DashboardDetails.tsx
  src/screens/OwnerImage/AddImages.tsx
  src/screens/Ownereditprofile/OwnerEditProfile.tsx
Labels: Component Test

#250 testing of analytics date picker 94% is done
  __tests__/atoms/AnalyticsDatePicker/AnalyticsDatePicker.test.tsx
  src/components/atoms/AnalyticsDatePicker.tsx
Labels: Component Test

#251 test: Toggle button 85% covered
  __tests__/atoms/SubcategoryDropdown/SubcategoryDropodown.test.tsx
  __tests__/atoms/ToggleButton/ToggleButton.test.tsx
  src/components/atoms/Colorscheme/Togglebutton.tsx
  src/constants/Apis.ts
Labels: code change, Component Test

#252 Test: AnalyticsDropdown and Sizeselect testing done with 91% and 82%
  .scannerwork/report-task.txt
  __tests__/atoms/AnalyticsDropdown/AnalyticsDropdown.test.tsx
  __tests__/atoms/Sizeselect/Sizeselect.test.tsx
  src/components/atoms/AnalyticsDropdown/AnalyticsDropdown.tsx
  src/components/atoms/Sizeselect.tsx
Labels: Component Test
